In [1]:
import numpy as np

In [2]:
x = np.array([1, 2, 3, 4, 5],   # 配列要素
             dtype = np.float   # 実数型(float)にする
             )
print(x)

[1. 2. 3. 4. 5.]


In [3]:
# ベクトルを作成

import numpy as np
x = np.array([1, 2, 3, 4, 5], dtype = np.float)
print(x + 10)

[11. 12. 13. 14. 15.]


In [4]:
# 足し算
x + 10

array([11., 12., 13., 14., 15.])

In [5]:
# 引き算
x - 1

array([0., 1., 2., 3., 4.])

In [6]:
# 掛け算
x*10

array([10., 20., 30., 40., 50.])

In [7]:
# 割り算
x/2

array([0.5, 1. , 1.5, 2. , 2.5])

In [8]:
# 割り算の結果を整数だけにする
x//2

array([0., 1., 1., 2., 2.])

In [9]:
# 剰余
x%2

array([1., 0., 1., 0., 1.])

In [10]:
# ベクトルの成分の累乗を求める

import numpy as np
x = np.array([1, 2, 3, 4, 5], dtype = np.float)
np.power(x, 2)

array([ 1.,  4.,  9., 16., 25.])

In [11]:
x**2

array([ 1.,  4.,  9., 16., 25.])

In [12]:
# ベクトルの成分の平方根を求める

x = np.array([1, 2, 3, 4, 5], dtype = np.float)
np.sqrt(x)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [13]:
# sin、cos、tanの計算

import numpy as np
x = np.array([0, 1], dtype = np.float)

In [14]:
np.sin(x)

array([0.        , 0.84147098])

In [15]:
np.sin(np.pi * 0.5)   # π/2のときのサインの値は1

1.0

In [16]:
np.cos(x)

array([1.        , 0.54030231])

In [17]:
np.cos(np.pi * 0.5)    # 0になる

6.123233995736766e-17

In [18]:
np.tan(x)

array([0.        , 1.55740772])

In [19]:
np.tan(np.pi * 0.5)    # 無限に発散する

1.633123935319537e+16

In [20]:
np.pi  # 円周率

3.141592653589793

In [21]:
# sin、cos、tanの逆関数の計算

import numpy as np
x = np.array([0.5, 1], dtype = np.float)

In [22]:
np.arcsin(np.sin(x)) # sinの逆関数

array([0.5, 1. ])

In [23]:
np.arccos(np.cos(x)) # cosの逆関数

array([0.5, 1. ])

In [24]:
np.arctan(np.tan(x)) # tanの逆関数

array([0.5, 1. ])

In [25]:
# ラジアンと度を相互変換する

import numpy as np
x = np.array([90, 180, 270], dtype = np.float)

In [26]:
np.radians(x)              # ラジアンに変換

array([1.57079633, 3.14159265, 4.71238898])

In [27]:
np.deg2rad(x)              # ラジアンに変換

array([1.57079633, 3.14159265, 4.71238898])

In [28]:
np.rad2deg(np.deg2rad(x))  # ラジアンを度に変換

array([ 90., 180., 270.])

In [29]:
# 切り捨て、切り上げ、四捨五入を行う

import numpy as np
x = np.array([-1.8, -1.4, -1.0, -0.6, -0.2, 0., 0.2, 0.6, 1.0, 1.4, 1.8])

In [30]:
np.floor(x)  # 切り捨て(値が小さい方の整数にする)

array([-2., -2., -1., -1., -1.,  0.,  0.,  0.,  1.,  1.,  1.])

In [31]:
np.trunc(x)  # 切り捨て(小数部分を切り捨てる)

array([-1., -1., -1., -0., -0.,  0.,  0.,  0.,  1.,  1.,  1.])

In [32]:
np.ceil(x)   # 切り上げ（大きい方の整数にする)

array([-1., -1., -1., -0., -0.,  0.,  1.,  1.,  1.,  2.,  2.])

In [33]:
np.round(x)  # 四捨五入

array([-2., -1., -1., -1., -0.,  0.,  0.,  1.,  1.,  1.,  2.])

In [34]:
np.around(x)  # 四捨五入

array([-2., -1., -1., -1., -0.,  0.,  0.,  1.,  1.,  1.,  2.])

In [35]:
np.rint(x)    # 四捨五入

array([-2., -1., -1., -1., -0.,  0.,  0.,  1.,  1.,  1.,  2.])

In [36]:
np.fix(x)     # 0に近いほうの整数をとる

array([-1., -1., -1., -0., -0.,  0.,  0.,  0.,  1.,  1.,  1.])

In [37]:
# 最大値、最小値、分散、標準偏差を求める

import numpy as np
x = np.array([35, 40, 45, 50, 55, 60], dtype = np.float)

In [38]:
print('最大値　: ', np.max(x))
print('最小値　: ', np.min(x))
print('平均値　: ', np.mean(x))
print('分　散　: ', np.var(x))
print('標準偏差: ', np.std(x))

最大値　:  60.0
最小値　:  35.0
平均値　:  47.5
分　散　:  72.91666666666667
標準偏差:  8.539125638299666


In [39]:
# 不偏分散、不偏標準偏差を求める
print('不偏分散　　: ', np.var(x, ddof=1))
print('不偏標準偏差: ', np.std(x, ddof=1))

不偏分散　　:  87.5
不偏標準偏差:  9.354143466934854
