In [1]:
# 行列を作成する

import numpy as np
mtx = np.array([[1, 2, 3],         # 3×3の行列を作成
                [4, 5, 6],
                [7, 8, 9]],
               dtype = np.float)

In [2]:
mtx

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [3]:
# 行列のスカラー演算

import numpy as np
mtx = np.array([[1, 2, 3],        # 3×3の行列を作成
                [4, 5, 6],
                [7, 8, 9]],
               dtype = np.float)

In [4]:
mtx + 10       # 足し算

array([[11., 12., 13.],
       [14., 15., 16.],
       [17., 18., 19.]])

In [5]:
mtx - 10        # 引き算

array([[-9., -8., -7.],
       [-6., -5., -4.],
       [-3., -2., -1.]])

In [6]:
mtx*2          # 乗算

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.],
       [14., 16., 18.]])

In [7]:
mtx/2          # 除算

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

In [8]:
mtx%2          # 剰余

array([[1., 0., 1.],
       [0., 1., 0.],
       [1., 0., 1.]])

In [9]:
# 行列の成分へのアクセス

import numpy as np
mtx = np.array([[1, 2, 3],  # 3×3の行列を作成
                [4, 5, 6],  # dtypeを指定しない場合は
                [7, 8, 9]]  # 成分の値に対応した型になる
              )

In [10]:
mtx.dtype       # データの型を確認

dtype('int32')

In [11]:
mtx[0]          # 1行目のすべての成分

array([1, 2, 3])

In [12]:
 mtx[0,]         # 1行目のすべての成分

array([1, 2, 3])

In [13]:
mtx[0, :]       # 1行目のすべての成分

array([1, 2, 3])

In [14]:
mtx[:, 0]       # 1列目のすべての成分

array([1, 4, 7])

In [15]:
mtx[1, 1]       # 2行、2列の成分

5

In [16]:
mtx[0:2, 0:2]   # 1行～2行、1列～2列の部分行列を抽出

array([[1, 2],
       [4, 5]])

In [17]:
# 行列の成分の集計

import numpy as np
mtx = np.array([[10, 20, 30],  # 3×3の行列を作成
                [40, 50, 60],
                [70, 80, 90]]
              )

In [18]:
np.max(mtx)          # 全成分の最大値

90

In [19]:
np.min(mtx)          # 全成分の最小値

10

In [20]:
np.sum(mtx)          # 全成分の合計

450

In [21]:
np.mean(mtx)         # 全成分の平均

50.0

In [22]:
# 行列の列ごと、行ごとの集計
np.sum(mtx, axis=0)  # 列ごとの合計

array([120, 150, 180])

In [23]:
np.mean(mtx, axis=0) # 列ごとの平均

array([40., 50., 60.])

In [24]:
np.sum(mtx, axis=1) # 行ごとの合計

array([ 60, 150, 240])

In [25]:
np.mean(mtx, axis=1) # 行ごとの平均

array([20., 50., 80.])

In [26]:
# 行列の成分どうしの足し算、引き算

import numpy as np
a = np.array([[1, 2],   # 2×2の行列を作成
              [3, 4]]
             )
b = np.array([[4, 3],   # 2×2の行列を作成
              [2, 1]]
            )

In [27]:
a + b                   #　成分どうしの足し算

array([[5, 5],
       [5, 5]])

In [28]:
a - b                   # 成分どうしの引き算

array([[-3, -1],
       [ 1,  3]])

In [29]:
# 行列どうしのアダマール積を求める

import numpy as np
a = np.array([[2, 3],  # 2×2の行列を作成
              [2, 3]]
            )
b = np.array([[3, 4],  # 2×2の行列を作成
              [5, 6]]
            )

In [30]:
a*b                  # アダマール積を求める

array([[ 6, 12],
       [10, 18]])

In [31]:
# 行列どうしの積を求める

import numpy as np
a = np.array([[1, 2],  # 2×2の行列を作成
              [3, 4]]
            )
b = np.array([[5, 6],  # 2×2の行列を作成
              [7, 8]]
            )

In [32]:
np.dot(a, b)           # 行列の積を求める

array([[19, 22],
       [43, 50]])

In [33]:
# ゼロ行列と単位行列の積の法則

import numpy as np
a = np.array([[2, 3, 4],  # 3×3の正方行列を作成
              [5, 6, 7],
              [8, 9, 1]]
              )
zero = np.zeros((3, 3))    # 3×3のゼロ行列
unit = np.identity(3)      # 3×3の単位行列

In [34]:
zero

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [35]:
unit

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
a*zero                     # AO = Oの法則

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [37]:
np.dot(a, unit)            # AE = EA = Aの法則

array([[2., 3., 4.],
       [5., 6., 7.],
       [8., 9., 1.]])

In [38]:
# 転置行列を求める

import numpy as np
a = np.array([[1, 2, 3],  # 2×3の行列を作成
              [4, 5, 6]]
            )

In [39]:
np.transpose(a)           # 転置行列を求める

array([[1, 4],
       [2, 5],
       [3, 6]])

In [40]:
# 逆行列を求める

import numpy as np
a = np.array([[1, 2],  # 2×2の行列を作成
              [3, 4]]
            )

In [41]:
inv = np.linalg.inv(a) # 逆行列を求める
print(inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [42]:
np.dot(a, inv)         # AB = E、BA = Eとなるのか確かめる

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])